import fs from 'fs';
import { execSync } from 'child_process';

const dataDir = './data';
const reportsDir = './reports';

if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir);

const files = fs.readdirSync(dataDir).filter(f => f.startsWith('research-')).sort().reverse();

if (files.length === 0) {
    console.log("No research data found.");
    process.exit(0);
}

const latestFile = `${dataDir}/${files[0]}`;
const content = fs.readFileSync(latestFile, 'utf8');

const dateStr = new Date().toLocaleDateString();
const reportContent = `# AI Trend Report - ${dateStr}\n\nGenerated by Milk AI Partner.\n\n${content}\n\n---
*Automated update via OpenClaw*`;

const reportFilename = `${reportsDir}/report-${new Date().toISOString().split('T')[0]}.md`;
fs.writeFileSync(reportFilename, reportContent);
console.log(`Report generated: ${reportFilename}`);

// Push to GitHub
try {
    execSync('git add . && git commit -m "Auto-update: New trend report" && git push');
    console.log("Pushed to GitHub successfully.");
} catch (e) {
    console.log("Git push failed (maybe no changes or auth issue).");
    console.error(e.message);
}
